# Generated by Django 2.2.4 on 2019-10-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('usuario', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
